apiVersion: v2
name: monitoring
description: A Helm chart for monitoring components
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 79.7.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    alias: prometheus
