apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: default
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: stirfry/platform-components/argocd/argocd-applications
    repoURL: https://github.com/marcboudreau/stirfry.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: environmentName
          value: {{ required "environmentName is required" .Values.environmentName }}
