apiVersion: v2
name: argocd
description: A Helm chart for ArgoCD
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 9.1.3
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
