apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    type: platform
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: platform-components/monitoring
    repoURL: https://github.com/marcboudreau/stirfry.git
    targetRevision: HEAD
    helm:
      releaseName: monitoring
      valueFiles:
        - base-values.yaml
        - {{ .Values.environmentName }}-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
