apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: {{ .Values.namespace | default "platform" }}
spec:
  instances: 3

  storage:
    size: 1Gi

  managed:
    roles:
      - name: pgbouncer_auth
        connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        comment: "Role used by pgbouncer to check client credentials"
        inRoles:
          - pg_read_all_stats
          - pg_read_all_settings
