apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgresql
  namespace: {{ .Values.namespace | default "platform" }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgresql
  podMetricsEndpoints:
    - port: metrics
